name: CI|CD éƒ¨ç½²æ–‡æ¡£
permissions:
  contents: write
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: build vite press
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: è¯»å–ä»“åº“å†…å®¹ ðŸ‘“
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: è®¾ç½® Node.js ðŸŽ¶
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: å®‰è£… yarn ðŸ¸
        run: npm install --global yarn

      - name: æž„å»ºæ–‡æ¡£ ðŸ”¨
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          yarn install
          yarn run docs:build
          > docs/.vitepress/dist/.nojekyll

      - name: éƒ¨ç½²æ–‡æ¡£ ðŸ‘Œ
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: docs/.vitepress/dist
